CREATE TABLE book
(
    id         SERIAL PRIMARY KEY,
    title      VARCHAR(255) NOT NULL,
    author_id  INT          NOT NULL REFERENCES author (id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
