ALTER TABLE author
    ADD COLUMN first_name VARCHAR(255),
ADD COLUMN last_name VARCHAR(255);

ALTER TABLE author
DROP COLUMN name;

ALTER TABLE author
    ALTER COLUMN first_name SET NOT NULL,
ALTER COLUMN last_name SET NOT NULL;